### ISSUE TITLE
Session与PersistenceContext

### ISSUE THREAD

**Issue by haoqi123** [zhangzhenhuajack/spring-boot-guide#1]
老师你好，我看完你在拉勾教育 《Spring Data JPA原理与实战》21章节的内容有些疑问，
`PersistenceContext 是持久化上下文，是 JPA 协议定义的，而 Hibernate 的实现是通过 Session 创建和销毁的，也就是说一个 Session 有且仅有一个 PersistenceContext`
关于这句话中的Session是否是web对象生命周期中的Session?

**Comment by zhangzhenhuajack** [comment]
指的是hibernate里面的session上下文

**Comment by haoqi123** [comment]
> 指的是hibernate里面的session上下文

好的，谢谢老师！
